### ISSUE TITLE
Include pre-release versions if dependency manifest uses pre-release versions

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli#113]
I suspect that the cause of the negatives values that we're seeing in #85 are because the dependency manifest is referencing pre-release versions of a dependency which are newer than the latest stable release. That would result in a negative LibYear.

To combat that, let's assume that if the manifest references a pre-release version, then they want to absolute latest version of that dependency even if it is a pre-release. 

Example time:

|Manifest|Latest stable|Latest unstable|Value to use|
|--------|-------------|----------------|------------|
|1.0-rc1|0.9|1.0-rc3|1.0-rc3|
|0.8|0.9|1.0-rc3|0.9|

**Comment by nickiemc** [comment]
Relevant example test data from running against https://github.com/binux/pyspider:

**Date: 2014-03-01, Manifest SHA: fcda3770fd36b3a7c3fe34796aea9365e5c2d42a**
- Name: [pycurl](https://pypi.org/project/pycurl/#history)
- RepoVersion: 7.19.3.1
- RepoVersionPublishedAt: 2014-02-06
- LatestVersion: 7.19.3
- LatestPublishedAt: 2014-01-10
- Value: -0.07409021435819381 

***

**Date: 2019-11-01, Manifest SHA: 0738a5b464767952f0c71dba013228c5d3f5464c**
- Name: [pycurl](https://pypi.org/project/pycurl/#history)
- RepoVersion: 7.43.0.3
- RepoVersionPublishedAt: 2019-06-17
- LatestVersion: 7.43.0
- LatestPublishedAt: 2016-02-05
- Value: -3.3643610159817348

**Comment by nickiemc** [comment]
Relevant example test data from running `Acceptance.ComposerWithoutGitHistory` test:

**Date: 2020-01-01T00:00:00, ManifestSHA: N/A**
- Name: scrivo/highlight.php
- RepoVersion: 9.17.1.0
- RepoVersionPublishedAt: 2019-12-13
- LatestVersion: 9.12.0
- LatestPublishedAt: 2017-11-15
- Value: -2.0767123287671234

**Comment by nickiemc** [comment]
Merged into `main`.
