### ISSUE TITLE
Move CLI to new repo and license under AGPL license

### ISSUE THREAD

**Issue by nickiemc** [corgibytes/freshli#133]
Per discussions with the leadership team, the project license for this repository will remain MIT. The CLI should be moved to a new repository that will adopt the [AGPL](https://www.gnu.org/licenses/agpl-3.0.en.html) license.

**Comment by mscottford** [comment]
https://github.com/freshli-cli has been created for this purpose. It just needs to be populated.

**Comment by dan-hein** [comment]
I am currently holding on creating a PR for this issue until the Freshli.Cli PR has been reviewed as these changes will remove functionality from Freshli.Core and place them within Freshli.Cli.
