### ISSUE TITLE
Failing Acceptance tests

### ISSUE THREAD

**Issue by doughertym** [corgibytes/freshli#19]
The test case `DrupalComposerWithoutGitHistory` fails with the following:

```
Assert.Equal() Failure
                      ↓ (pos 12)
Expected: 2020/01/01: 3.214\n
Actual:   2020/01/01: 2.792\n
                      ↑ (pos 12)
   at LibMetrics.Test.Acceptance.DrupalComposerWithoutGitHistory() in /Volumes/home/mikedougherty/workspace/Corgibytes/libmetrics/LibMetrics.Test/Acceptance.cs:line 252
```

Some research into this indicates that this is an issue with the package manifest itself. The fixture has `drupal/drupal:7.69.0` as the dependency. And there are a couple issues with logic attempting to find the latest version. 

~1. The `MulticastComposerRepository` returns the first `VersionInfo` found for the package regardless of version constraints in the Manifest. Which means it will return major releases (i.e. 8.x) when it should only return minor and patch updates (major releases normally have breaking changes).~

2\. Even if the `MulticastComposerRepository` would return the correct major version, it would still have an issue with the `DatePublished` value. A good example of this is `drupal/drupal:7`, which is retrieved only from https://packages.drupal.org/7 (nothing on packagist.org for this version). The `DatePublished` value is retrieved from `extra.drupal.datestamp`, however, this value does not actually reflect when this release was made. Looking at the source, the commit for v7.69 was made on Dec. 18, 2019 (https://git.drupalcode.org/project/drupal/-/commits/7.69). But the version info from the package.json has a `datestamp` of `2020-05-20 16:06:39`

**Comment by mscottford** [comment]
1. Ignoring the constraints in the manifest is the correct behavior. The metric is an attempt to trying and communicate how far behind the latest version a particular package reference is.

2. Ah! Good find! I remember having a tough time trying to figure out the published date for those packages... I guess we'll have to track down another source. I ended up having to use screen-scraping to get the correct dates for the python packages. Not the most stable solution... but if that's all that you have...

**Comment by doughertym** [comment]
Re: 1. -- Ah, OK. I'll edit the issue. 

Re: 2. -- Would it make sense read the repo? The composer package information contains a reference to the source (git repo and tag/commit hash). It would take some work, but we _could_ get the date of the commit. If it's on Github and they use versions, we could also read that. So I suppose there are ways, just rather complicated to get them all sorted.

**Comment by mscottford** [comment]
I think we need to basically figure out what http requests would be run during a [`composer update`](https://getcomposer.org/doc/03-cli.md#update-u).

Perhaps using a HTTP debugging proxy like https://proxyman.io. Thoughts?

**Comment by doughertym** [comment]
> I think we need to basically figure out what http requests would be run during a [`composer update`](https://getcomposer.org/doc/03-cli.md#update-u).
> 
> Perhaps using a HTTP debugging proxy like https://proxyman.io. Thoughts?

Hmm, that's a good idea. I'll have a look and see how that could help.

**Comment by doughertym** [comment]
@mscottford I did some investigation (using `composer` as per your idea). I does not seem as though `composer` checks for dates when determining the most recent version. I was not able to find anything in `composer` that would help us make better decisions based on dates. They seem to do it all based on the version and version constraints. 

A couple things I did find out in researching this is that the versions causing the error are actually the latest versions for the test `date` provided. So I've updated the expected data files for these tests (see https://github.com/corgibytes/freshli/commit/3fd1eef5bf26efacd14600a93068764960b5c819) and fixed a couple bugs. So I think this will do the trick. But please review PR #34 and let me know if you think it needs adjustments.
