### ISSUE TITLE
Add warning message when package is missing

### ISSUE THREAD

**Issue by doughertym** [corgibytes/freshli#25]
When a package is not found in `VersionInfo.LatestAsOf` there should be a warning message sent to the Logger. 

For example, line 18 of `Freshli/Languages/Ruby/RubyGemsRepository.cs` might be:
```
      var firstCandidate = candidates.FirstOrDefault();
      if (firstCandidate != null)
      {
        return new VersionInfo(
          firstCandidate.Number,
          firstCandidate.CreatedAt.Date);
      } else {
        logger.Warn($"{name} was not found for {date}.");
      }
```

Relates to Issue #15 and Issue #8

**Comment by nickiemc** [comment]
Addressed in PR #54.
