### ISSUE TITLE
Strengthen error page

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli#59]
In `Freshli.Web` the error handling page and corresponding model are the result of running `dotnet new mvc`. These need to be improved to something that's more production ready.

- `ShowRequestId` in the `ErrorViewModel` needs to be renamed to something that sounds like a predicate field such as `ShouldShowRequestId` or `IsRequestIdSet`
- Exception messages should only be shown when the application is running in `Development` mode. In `Production` mode, the site should just report that there's been an error.
- 5XX errors should be logged to a service such as `honeybadger` (but not `honeybadger`, because it does not support .NET applications)

**Comment by nickiemc** [comment]
I created [PR #56](https://github.com/corgibytes/freshli-web/pull/56) to update the error page.

Regarding using a different error page for development, this logic [already exists](https://github.com/corgibytes/freshli-web/blob/main/Freshli.Web/Startup.cs#L65). To test locally, setting `ASPNETCORE_ENVIRONMENT` in a `.env` file did not work. Instead, I had to set it in the `Freshli.Web` profile in `launchSettings.json`.

Regarding using a service to monitor errors, this issue has been logged separate as #117.

**Comment by nickiemc** [comment]
Deployed to production.
